### selectAllPost(공지 및 게시글 전체조회)
GET http://localhost:8080/boards


### selectPost(게시글 상세 조회)
GET http://localhost:8080/boards/213

### insertBoard()
POST http://localhost:8080/boards
Content-Type: application/json

{
  "postTitle": "우리당당",
  "postContext": "당당구리당당",
  "postCategory": "자유",
  "postDate": "2024.06.25",
  "postStatus": "Y",
  "userCode": 3,
  "userNick": "어디가냥"
}

### chatAllComment(댓글)
GET http://localhost:8080/comments