### 전체 큐레이션 리스트 조회
GET http://localhost:8080/curationList

### 사용자별 큐레이션 리스트 조회
GET http://localhost:8080/curations?userCode=

### 사용자별 강아지별 큐레이션 리스트 조회
GET http://localhost:8080/curationsdog?userCode=&curationName=


