
### selectAllProducts(사료 전체 조회)
GET http://localhost:8080/products

### selectProductsByNo(사료 상세 조회)
GET http://localhost:8080/products/3

### comparisonProducts(사료 비교)
GET http://localhost:8080/products/comparison?prodCode1=2&prodCode2=30

### searchProducts(사료 검색)
GET http://localhost:8080/products/search?value=&prodRecom=&prodAge=&prodCook=&prodSize=&prodEffi=&prodPrice=

### productSearch(사료 검색)
GET http://localhost:8080/products/prodsearch?type=prodName&input=청어

### insertProduct(사료 입력)
POST http://localhost:8080/products
Content-Type: application/json

{
  "prodCode": 0,
  "prodName": "prodName",
  "prodManufac": "prodManufac",
  "prodPrice": 1000,
  "prodAge": "전체",
  "prodEffi": "prodEffi1",
  "prodRecom": "소형견",
  "prodSite": "http://localhost:8080/products",
  "prodCook": "습식",
  "prodVolume": "1.6",
  "prodGrade": 1,
  "prodIngra": "prodIngra1",
  "prodSize": "13",
  "prodImage": "/images/admin/No Image Available.png"
}

### updateProduct(사료 수정)
PUT http://localhost:8080/products
Content-Type: application/json

{
  "prodCode": 20,
  "prodName": "prodName",
  "prodManufac": "prodManufac",
  "prodPrice": 1000,
  "prodAge": "전체",
  "prodEffi": "prodEffi1",
  "prodRecom": "소형견",
  "prodSite": "http://localhost:8080/products",
  "prodCook": "습식",
  "prodVolume": "1.6",
  "prodGrade": 1,
  "prodIngra": "prodIngra1",
  "prodSize": "13",
  "prodStatus": "N",
  "prodImage": "/images/admin/No Image Available.png"
}

### deleteProduct(사료 삭제)
DELETE http://localhost:8080/products/34