### 회원가입
POST http://localhost:8080/signup
Content-Type: application/json
Accept: */*

{
  "userId": "user04@gmail.com",
  "userPass": "qwer1234",
  "userNick": "티키타카",
  "userPhone": "010-1234-3345"
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json
Accept: */*

{
  "userId": "admin01@gmail.com",
  "userPass": "qwer1234"
}

### selectUserByCodeByAdmin
GET http://localhost:8080/admin/users/1

### selectAllUsersByAdmin
POST http://localhost:8080/admin/users
Content-Type: application/json

{
  "type": "user",
  "input": ""
}

### updateUserByAdmin
PUT http://localhost:8080/admin/users
Content-Type: application/json

{
  "userId": "admin3@gmail.com",
  "userPass": "admin03",
  "userNick": "크르릉댕댕콱콱",
  "userPhone": "010-9877-8766",
  "userSignup": "2024-06-24",
  "userLatest": "2024-06-24",
  "userAuth": "ADMIN"
}

### deleteUserByAdmin
DELETE  http://localhost:8080/admin/users/2

### checkInfo-email
POST http://localhost:8080/user/check
Content-Type: application/json

{
  "type": "email",
  "info": "user01@gmail.com"
}

### checkInfo-nick
POST http://localhost:8080/user/check
Content-Type: application/json

{
  "type": "nick",
  "info": "낭만고양이"
}

### checkInfo-phone
POST http://localhost:8080/user/check
Content-Type: application/json

{
  "type": "phone",
  "info": "010-1234-2345"
}


