### 회원가입
POST http://localhost:8080/signup
Content-Type: application/json
Accept: */*

{
  "userId": "user04@gmail.com",
  "userPass": "qwer1234",
  "userNick": "티키타카",
  "userPhone": "010-1234-3345"
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json
Accept: */*

{
  "userId": "user02@gmail.com",
  "userPass": "qwer1234"
}

### 로그아웃
POST http://localhost:8080/auth/logout
Authorization: BEARER eyJkYXRlIjoxNzIwMjY3MTc4NTQ5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJEb2dwYW1pbmVzIHRva2VuIDogMiIsInVzZXJOaWNrIjoi6rCc6ruM7ZWY64KY65GQ6rCcIiwidXNlckF1dGgiOiJVU0VSIiwiZXhwIjoxNzIwMjcwNzc4LCJ1c2VyQ29kZSI6Mn0.3BFj_iCTuvYPsk_VQ1evngghwPBVlIluPXmJC61g_mc
Refresh-Token: BEARER eyJkYXRlIjoxNzIwMjY3MTc4NTYyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJEb2dwYW1pbmVzIHJlZnJlc2ggdG9rZW4gOiAyIiwidXNlck5pY2siOiLqsJzqu4ztlZjrgpjrkZDqsJwiLCJ1c2VyQXV0aCI6IlVTRVIiLCJleHAiOjE3MjA4NzE5NzgsInVzZXJDb2RlIjoyfQ.g3vWti2S4J8NMAeVmbgpsipcke6IY0sl5RbireU3YMk

### 토큰 재발급
POST http://localhost:8080/auth/refresh
Refresh-Token: BEARER eyJkYXRlIjoxNzIwMjY3OTQ3OTYwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJEb2dwYW1pbmVzIHJlZnJlc2ggdG9rZW4gOiAyIiwidXNlck5pY2siOiLqsJzqu4ztlZjrgpjrkZDqsJwiLCJ1c2VyQXV0aCI6IlVTRVIiLCJleHAiOjE3MjA4NzI3NDcsInVzZXJDb2RlIjoyfQ.SNZoMP-xHNSdgb1O31gHnUA3as5eFjfUFyBpJeNzNpY

### selectUserByCodeByAdmin
GET http://localhost:8080/admin/users/1

### selectAllUsersByAdmin
POST http://localhost:8080/admin/users
Content-Type: application/json

{
  "type": "user",
  "input": ""
}

### updateUserByAdmin
PUT http://localhost:8080/admin/users
Content-Type: application/json

{
  "userId": "admin3@gmail.com",
  "userPass": "admin03",
  "userNick": "크르릉댕댕콱콱",
  "userPhone": "010-9877-8766",
  "userSignup": "2024-06-24",
  "userLatest": "2024-06-24",
  "userAuth": "ADMIN"
}

### deleteUserByAdmin
DELETE  http://localhost:8080/admin/users/2

### checkInfo-email
POST http://localhost:8080/user/check
Content-Type: application/json

{
  "type": "email",
  "info": "user01@gmail.com"
}

### checkInfo-nick
POST http://localhost:8080/user/check
Content-Type: application/json

{
  "type": "nick",
  "info": "낭만고양이"
}

### checkInfo-phone
POST http://localhost:8080/user/check
Content-Type: application/json

{
  "type": "phone",
  "info": "010-1234-2345"
}

### updateUserPwd
PUT http://localhost:8080/user/change/pwd
Content-Type: application/json

{
  "id" : "user01@gmail.com",
  "pwd" : "qwer1233"

}


