### 회원가입
POST http://localhost:8080/signup
Content-Type: application/json
Accept: */*

{
  "userId": "user03@gmail.com",
  "userPass": "qwer1234",
  "userNick": "고담시티",
  "userPhone": "010-3321-4455",
  "userSignup": "2024-06-26",
  "userLatest": "2024-06-26",
  "userAuth": "USER"
}

### 로그인
POST http://localhost:8080/login
Content-Type: application/json
Accept: */*

{
  "userId": "user03@gmail.com",
  "userPass": "qwer1234"
}

### selectUserByCodeByAdmin
GET http://localhost:8080/admin/users/1

### selectAllUsersByAdmin
POST http://localhost:8080/admin/users
Content-Type: application/json

{
  "type": "user",
  "input": ""
}

### updateUserByAdmin
PUT http://localhost:8080/admin/users
Content-Type: application/json

{
  "userId": "admin3@gmail.com",
  "userPass": "admin03",
  "userNick": "크르릉댕댕콱콱",
  "userPhone": "010-9877-8766",
  "userSignup": "2024-06-24",
  "userLatest": "2024-06-24",
  "userAuth": "ADMIN"
}

### deleteUserByAdmin
DELETE  http://localhost:8080/admin/users/2